//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoList.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemList
    {
        public int ListItemId { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
        public Nullable<System.DateTime> DateDue { get; set; }
        public Nullable<int> AmountItem { get; set; }
        public Nullable<decimal> PricePerItem { get; set; }
        public int ItemId { get; set; }
        public int SupplierId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Suppliier Suppliier { get; set; }
    }
}
